services:
  - type: web
    name: quantum-radio
    runtime: static
    buildCommand: chmod +x build.sh && ./build.sh
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 